### PR TITLE
Upgrade to duktape 2.0.2

### PR DESCRIPTION
**Pull request by jeromegn**
I downloaded 2.0.2, replaced the appropriate files, `make libduktape` and it seemed to "just work" if I run the `crystal spec` suite.

Hopefully travis will confirm this :)

### CODE REVIEW

**Comment by jeromegn** [comment]
I guess travis didn't like it.

I've been able to run the spec locally just fine. Travis is not really helpful (no trace in the logs.)

Any thoughts?

**Comment by jessedoyle** [comment]
@jeromegn - Awesome! This is great! I haven't looked at the PR yet, but moving to >= `v2` has been on my TODO list for some time. 

I'll try to set aside some time in the next couple of days to take a look!

Thanks.

**Comment by jessedoyle** [comment]
As for the travis failures, what happens if you try to run this locally on your branch?

```
make clean cleanlib
make libduktape
make spec
```
?

**Comment by jeromegn** [comment]
Oh, derp.

I got the same error. Looks like I wasn't cleaning up the lib correctly.

I ran `crystal spec` to see the actual error:

```
$ crystal spec
Undefined symbols for architecture x86_64:
  "_duk_fatal", referenced from:
      _*Duktape::Context@Duktape::API::ErrorHandling#fatal<Int32, String>:Nil in D-uktape5858C-ontext.o
     (maybe you meant: _duk_fatal_raw)
  "_duk_is_null_or_undefined", referenced from:
      _*Duktape::Context@Duktape::API::Type#is_null_or_undefined<Int32>:Bool in D-uktape5858C-ontext.o
  "_duk_push_string_file_raw", referenced from:
      _*Duktape::Context@Duktape::API::Eval#eval_file<String>:Int32 in D-uktape5858C-ontext.o
      _*Duktape::Context@Duktape::API::Push#push_string_file<String>:String in D-uktape5858C-ontext.o
      _*Duktape::Context@Duktape::API::Eval#eval_file_noresult<String>:Int32 in D-uktape5858C-ontext.o
  "_duk_throw", referenced from:
      _*Duktape::Context@Duktape::API::ErrorHandling#throw:Nil in D-uktape5858C-ontext.o
     (maybe you meant: _duk_throw_raw)
  "_duk_to_defaultvalue", referenced from:
      _*Duktape::Context@Duktape::API::Coercion#to_defaultvalue<Int32, Int32>:Nil in D-uktape5858C-ontext.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o "/Users/jerome/.cache/crystal/crystal-run-spec.tmp" "${@}"  -rdynamic  -L/Users/jerome/projects/github.com/jeromegn/duktape.cr/src/.build/lib -L/Users/jerome/projects/github.com/jeromegn/duktape.cr/src/.build/include -lduktape -lm -lxml2 -lpcre -lgc -lpthread /usr/local/Cellar/crystal-lang/0.21.1/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/lib -L/usr/local/lib`
```

**Comment by jeromegn** [comment]
Ok, this is slightly more work than I expected. Especially since I don't have a great understanding of how duktape works.

It looks like only a few functions have been fully deprecated, but I can't be sure if others haven't had changes in arguments and such.

Easiest is to delete the deprecated ones. A bit harder reimplement like this: https://github.com/svaarala/duktape/blob/master/extras/duk-v1-compat (or straight up include those extras in the c bindings)

`duk_is_null_or_undefined` can be reimplemented using `duk_require_type_mask` if it's needed.

The trickiest one is `duk_push_string_file_raw`, the compat implementation is a bit more complicated: https://github.com/svaarala/duktape/blob/master/extras/duk-v1-compat/duk_v1_compat.c#L25-L66

Anyway! I might take a look later, but I consider this PR closed.

**Comment by jessedoyle** [comment]
Yea, there's a bit of work to be done here to fully migrate. I'm going to start a `2.0.X` branch so that this can be easily worked on.

Of course any PRs are welcome!

Thankfully, the Duktape team keeps great changelogs: https://github.com/svaarala/duktape/blob/master/RELEASES.rst

**Comment by jessedoyle** [comment]
Just an FYI - I'm starting work on migrating to `2.0.2` here: https://github.com/jessedoyle/duktape.cr/compare/duktape-2.0.

Right now I've got the C code compiling correctly on my machine - there's still a ton of work to do on the actual Crystal bindings.

I'll try to keep at it - hopefully I'll get the specs running within a relatively short period of time.

PRs are welcome into this branch if anyone wishes to contribute!

Thanks

**Pull request closed without merging**
